const { chromium } = require('/opt/node22/lib/node_modules/playwright');
(async () => {
  const b = await chromium.launch({ executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
  const p = await (await b.newContext({viewport:{width:1200,height:1000}})).newPage();
  const errs=[]; p.on('pageerror',e=>errs.push(e.message)); p.on('console',m=>{if(m.type()==='error'&&!/Failed to load resource/.test(m.text()))errs.push('C:'+m.text());});
  await p.goto('http://localhost:4321/mentor?demo=1', {waitUntil:'domcontentloaded'});
  await p.addStyleTag({content:'.hidden{display:none !important}'});
  await p.waitForTimeout(800);
  await p.click('#studentList [data-id]'); await p.waitForTimeout(400);
  const metricsHiddenDefault = await p.evaluate(()=>document.getElementById('metricsBlock').classList.contains('hidden'));
  await p.selectOption('#se_type','Metrics check'); await p.waitForTimeout(150);
  const metricsShown = await p.evaluate(()=>!document.getElementById('metricsBlock').classList.contains('hidden'));
  await p.selectOption('#se_type','Student session'); await p.waitForTimeout(150);
  const metricsHiddenAgain = await p.evaluate(()=>document.getElementById('metricsBlock').classList.contains('hidden'));
  await p.click('.tab[data-tab=reports]'); await p.waitForTimeout(400);
  await p.fill('#meMonth','2026-06');
  await p.click('#meRunBtn'); await p.waitForTimeout(500);
  const nums = await p.evaluate(()=>({ ...lastMonthEnd.num, serviceHours:+lastMonthEnd.num.serviceHours.toFixed(1), missing: lastMonthEnd.missing.map(s=>s.last_name) }));
  const resultsText = await p.textContent('#meResults');
  console.log(JSON.stringify({ metricsHiddenDefault, metricsShown, metricsHiddenAgain, nums, hasMissingWarning: resultsText.includes('Walker'), XLSXavailable: await p.evaluate(()=>typeof window.XLSX), errs }, null, 2));
  await b.close();
})().catch(e=>{console.error('FATAL',e.message);process.exit(1);});
